Task.create(content: "Initally, initials can be found but not on any ground. This one is different, being sourrounded by liquid.", code:"125905")
Task.create(content: "There is something in a tree, it must be recieved. If a hint you desire, look for the one with the color fire", code:"144")
Task.create(content: "Vroom Vroom, there is something wrong with this broom.", code:"af4521")
Task.create(content: "Science is cool, there is something in the pool. Align these you might, by the color of the light.", code:"#00-100")
Task.create(content: "Cycles are best for a figure of eight, but remember to keep looking straight.", code:"pappas")
Task.create(content: "Where sports are played a bubble was made, pass this you may. Don't let it pop! After passing to all you may stop", code:"02473bd")
Task.create(content: "Leafy greens are nice, but get this in your eyes you might cry. If color is your wish subtract blue from green in a dish.", code:"asa4197")
Task.create(content: "Shoulders and a Head covered in red, you can open me I am dead. ", code:"happybirthday")
Task.create(content: "For you three, there is a treat. A trio of glee, protected by me. Look to the north, there is a bridge with a gift for yee. ", code:"happybirthday")